apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: vithatidemo 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: vithatidemo 
    spec:
      containers:
        - name: vithatidemo 
          image: jikuma.azurecr.io/vithatidemo
          ports:
          - containerPort: 80